### PR TITLE
Ps 0.1.2 dev branch

### PR DESCRIPTION
**Pull request by psantos1113**
The 0.1.2 version now has feature parity with other CI's so this will be the 1.0.0 release.  This is the set of changes to generate the risk report.  It relies on the hub-atlassian-config refapp plugin.  Fix issues working with remote agents as well.

### CODE REVIEW

**Comment by psantos1113** [comment]
@jrichardBD @ekerwin @stevebillings @akamen Here's the pull request for the bamboo changes

**Comment by jrichardBD** [comment]
Looks good

**Comment by stevebillings** [comment]
Looks good.

**Comment by akamen** [comment]
Ship it!

**Comment by utsavsanghani** [comment]
Take it and go!

________________________________
[cid:E11C807F-F00A-4500-993A-D8A68B318574]
Utsav Sanghani
Product Manager
Black Duck Software, Inc.
800 District Avenue
Burlington, MA 01803
E: usanghani@blackducksoftware.com
O: +1.781.891.5100
M: +1.617.712.5830
Skype: utsav.sanghani.bds
www.blackducksoftware.com<http://www.blackducksoftware.com/>

**Comment by stevebillings** [comment]
Looks good

**Pull request merged**
