### PR TITLE
Secure token fix

### PR DESCRIPTION
**Pull request by psantos1113**
Changes to get the plugin to work with 5.10 servers and higher due to breaking API changes.

### CODE REVIEW

**Comment by psantos1113** [comment]
@ekerwin @akamen @jrichardBD @stevebillings  
Please review the plugin changes when possible.

**Comment by psantos1113** [comment]
@ekerwin @akamen @jrichardBD @stevebillings  
Updated the pull request based on Eric's feedback.

**Comment by ekerwin** [comment]
looks good to me!

**Comment by stevebillings** [comment]
looks good.

**Comment by jrichardBD** [comment]
@psantos1113  looks good

**Pull request merged**
